default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ticketfy_dev

test:
  <<: *default
  database: ticketfy_test

production:
  <<: *default
  database: ticketfy_prod
