version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        RAILS_ENV: development
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache # share cache between containers for dev purposes and fix problems with permission when running with root user
      - ./docker/.env.development:/app/.env.development
      - ./docker/.env.test:/app/.env.test
    environment:
      HISTFILE: /app/log/.bash_history
      EDITOR: vi
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  runner:
    <<: *app
    command: /bin/bash
    ports:
      - '3001:3000'

  tester:
    <<: *app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        RAILS_ENV: test
        ENVIRONMENT_PACKAGES: libc6-compat chromium chromium-chromedriver
    command: /bin/bash
    environment:
      DOCKER_MODE: 'true'
      HISTFILE: /app/log/.bash_history
      EDITOR: vi
    ports:
      - '3002:3000'

  postgres:
    container_name: postgres
    image: postgres:11.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
  rails_cache:
