version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/DockerfileTest
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - $HOME/Docker/Volumes/PostgresAlpine9.6:/var/lib/postgresql/data
