version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/application
    links:
      - db
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - $HOME/Docker/Volumes/PostgresAlpine9.6:/var/lib/postgresql/data
