version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  runner:
    <<: *app
    command: /bin/bash
    ports:
      - '3001:3001'

  postgres:
    container_name: postgres
    image: postgres:11.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:

