version: '3'

services:
  web:
    build: .
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - 3000:3000
    volumes:
      - .:/application
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 5433:5432
    volumes:
      - $HOME/Docker/Volumes/PostgresAlpine9.6:/var/lib/postgresql/data
